name: CI/CD for Flag Explorer API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_IMAGE_BACKEND: ghcr.io/${{ github.repository_owner }}/flag-explorer-api

jobs:
  test-and-build-backend:
    name: Test & Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flag-explorer-api
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install backend dependencies
        run: npm install --force --legacy-peer-deps
      - name: Run backend tests
        run: npm test:ci
      - name: Build backend application
        run: npm build
      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push backend Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./flag-explorer-api
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_BACKEND }}:latest
            ${{ env.DOCKER_IMAGE_BACKEND }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_BACKEND }}:latest
          cache-to: type=inline
